@ExchangeRate.API_HostAddress = http://localhost:5099

GET {{ExchangeRate.API_HostAddress}}/api/exchangerate/
Accept: application/json

###

GET {{ExchangeRate.API_HostAddress}}/api/exchangerate?startDate=01/03/2025&endDate=01/03/2025
Accept: application/json

###

GET {{ExchangeRate.API_HostAddress}}/weatherforecast/
Accept: application/json

###
