@baseUrl = http://localhost:5099

GET {{baseUrl}}/api/exchangerate/
Accept: application/json

###

GET {{baseUrl}}/api/exchangerate?startDate=01/03/2025&endDate=01/03/2025
Accept: application/json

###

GET {{baseUrl}}/weatherforecast/
Accept: application/json

###
